command-aliases: 'resolve'
messages-output: 'ACTION_BAR'
resolve:
  source-table:
    GEMS: gems
item:
  enabled: true
  material: 'SHEARS:0:1'
  name: '&f&lResolve Tool'
  lore:
  - '&f> &7Type:                    &fResolve Tool'
  - '&8&m                                              '
  - '&7Can resolve an item once if'
  - '&7this item is resolvable.'
  - ''
  - '&f&oDrag and drop on item'
  - '&f&oto open resolve menu.'
gui:
  title: '&4&l<&4&nResolve&4&l>'
  size: 54
  item-slot: 2
  source-slot: 6
  result-slots: '28,29,30,31,32,33,34,37,38,39,40,41,42,43'
  content:
    filler_black:
      material: 'STAINED_GLASS_PANE:15:1'
      skull-hash: ''
      enchanted: false
      name: ''
      lore: []
      slots: '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,35,36,44,45,46,47,48,49,50,51,52,53'
      type: NONE
    filler_yellow:
      material: 'STAINED_GLASS_PANE:1:1'
      skull-hash: ''
      enchanted: false
      name: ''
      lore: []
      slots: '3,5'
      type: NONE
    filler_orange:
      material: 'STAINED_GLASS_PANE:2:1'
      skull-hash: ''
      enchanted: false
      name: ''
      lore: []
      slots: '4,13'
      type: NONE
    hopper-result:
      material: 'HOPPER:0:1'
      skull-hash: ''
      enchanted: false
      name: '&6Result'
      lore: []
      slots: '22'
      type: NONE
    accept:
      material: 'STAINED_GLASS_PANE:5:1'
      skull-hash: ''
      enchanted: false
      name: '&a&l&nAccept'
      lore:
      - '&7The item will be resolved'
      - '&7and you will get some source'
      - '&7materials of that.'
      - '&8&m                                              '
      slots: '8'
      type: ACCEPT
    exit:
      material: 'STAINED_GLASS_PANE:14:1'
      skull-hash: ''
      enchanted: false
      name: '&c&l&nCancel'
      lore: []
      slots: '0'
      type: EXIT