cfg_version: 1.0
command-aliases: 'repair,qrep'
messages-output: ACTION_BAR
repair:
  effects:
    enabled: true
    effect: 'SPELL_WITCH'
  sounds:
    enabled: true
    sound: 'BLOCK_ANVIL_USE'
  types:
    EXP:
      enabled: true
      cost-per-unit: 0.1
    MATERIAL:
      enabled: true
      cost-per-unit: 0.02
    VAULT:
      enabled: true
      cost-per-unit: 1.33
  materials:
    ignore-items-with-meta: false
    materials-group:
      diamond:
      - 'DIAMOND'
      iron:
      - 'IRON_INGOT'
      gold:
      - 'GOLD_INGOT'
      stone:
      - 'STONE'
      - 'COBBLESTONE'
      wood:
      - 'WOOD'
      - 'LOG'
      stick:
      - 'STICK'
    materials-table:
      diamond:
        name: 'Diamond(s)'
        can-repair:
        - 'DIAMOND_*'
      iron:
        name: 'Iron Ingot(s)'
        can-repair:
        - 'IRON_*'
      gold:
        name: 'Gold Ingot(s)'
        can-repair:
        - 'GOLD_*'
      stone:
        name: 'Stone(s)'
        can-repair:
        - 'STONE_*'
      wood:
        name: 'Wood'
        can-repair:
        - 'WOOD_*'
      stick:
        name: 'Stick(s)'
        can-repair:
        - 'BOW'
anvil:
  enabled: true
  open-action: SHIFT_RIGHT
item:
  enabled: true
  material: 'IRON_AXE:0:1'
  name: '&f&lRepair Hammer'
  lore:
  - '&f> &7Type:                    &fRepair Tool'
  - '&8&m                                              '
  - '&7Can repair any item once with'
  - '&7custom durability.'
  - ''
  - '&f&oDrag and drop on item'
  - '&f&oto open repair menu.'
gui:
  title: '&4&l<&4&nRepair&4&l>'
  size: 54
  item-slot: 1
  source-slot: 7
  result-slot: 22
  repair-types:
    EXP:
      material: 'BOOK:0:1'
      skull-hash: ''
      name: '&7[&eRepair by Exp&7]'
      lore:
      - '&7> &fCost:           &e%cost% exp'
      - '&7> &fYou have:     &e%have% exp'
      - '&8&m                                              '
      - '&7Repairs an item by your exp points.'
      slots: '37'
      type: NONE
    MATERIAL:
      material: 'WORKBENCH:0:1'
      skull-hash: ''
      name: '&7[&6Repair by Material&7]'
      lore:
      - '&7> &fCost:           &6%cost% %mat%'
      - '&7> &fYou have:     &6%have% %mat%'
      - '&8&m                                              '
      - '&7Repairs an item by materials.'
      slots: '40'
      type: NONE
    VAULT:
      material: 'EMERALD:0:1'
      skull-hash: ''
      name: '&7[&aRepair by Money&7]'
      lore:
      - '&7> &fCost:           &a%cost%$'
      - '&7> &fYou have:     &a%have%$'
      - '&8&m                                              '
      - '&7Repairs an item by money.'
      slots: '43'
      type: NONE
  content:
    filler_black:
      material: 'STAINED_GLASS_PANE:15:1'
      skull-hash: ''
      enchanted: false
      name: ''
      lore: []
      slots: '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53'
      type: NONE
    filler_yellow:
      material: 'STAINED_GLASS_PANE:1:1'
      skull-hash: ''
      enchanted: false
      name: ''
      lore: []
      slots: '2,3,4,5,6,13'
      type: NONE
    filler_orange:
      material: 'STAINED_GLASS_PANE:2:1'
      skull-hash: ''
      enchanted: false
      name: ''
      lore: []
      slots: '19,20,21,23,24,25,28,31,34'
      type: NONE
    accept:
      material: 'STAINED_GLASS_PANE:5:1'
      skull-hash: ''
      enchanted: false
      name: '&a&l&nAccept'
      lore:
      - '&7The item will be repaired'
      - '&7if you can afford the repair.'
      - '&8&m                                              '
      - '&c&oDon''t forget to select'
      - '&c&othe repair type!'
      slots: '50'
      type: ACCEPT
    exit:
      material: 'STAINED_GLASS_PANE:14:1'
      skull-hash: ''
      enchanted: false
      name: '&c&l&nCancel'
      lore: []
      slots: '48'
      type: EXIT