cfg_version: 1.0
command-aliases: 'extractor'
messages-output: ACTION_BAR
extract:
  cost:
    default-cost:
      GEM: 250.0
      ESSENCE: 780.0
      RUNE: 460.0
    cost-per-lvl:
      GEM: 45.0
      ESSENCE: 80.0
      RUNE: 60.0
item:
  enabled: true
  material: 'IRON_AXE:0:1'
  name: '&f&lExtract Tool'
  lore:
  - '&f> &7Type:                    &fExtract Tool'
  - '&8&m                                               '
  - '&7Can extract an item from'
  - '&7the filled socket.'
  - ''
  - '&f&oDrag and drop on item'
  - '&f&oto open extract menu.'
gui:
  title: '&4&l<&4&nExtractor&4&l>'
  size: 54
  item-slot: 2
  source-slot: 4
  result-slot: 6
  socket-slots: '45,46,47,48,49,50,51,52,53'
  socket-name: '&7Extract: %name%'
  socket-lore:
  - '&7> &fCost:           &e$%cost%'
  - '&7> &fYou have:     &e$%have%'
  - '&8&m                                      '
  - '&7Extract the specified item.'
  socket-types:
    GEM:
      material: 'EMERALD:0:1'
      skull-hash: ''
      name: '&aExtract Gems'
      lore: []
      slots: '28'
      type: NONE
    RUNE:
      material: 'DIAMOND:0:1'
      skull-hash: ''
      name: '&bExtract Runes'
      lore: []
      slots: '31'
      type: NONE
    ESSENCE:
      material: 'REDSTONE:0:1'
      skull-hash: ''
      name: '&cExtract Essences'
      lore: []
      slots: '34'
      type: NONE
  content:
    filler_black:
      material: 'STAINED_GLASS_PANE:15:1'
      skull-hash: ''
      enchanted: false
      name: ''
      lore: []
      slots: '0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44'
      type: NONE
    filler_yellow:
      material: 'STAINED_GLASS_PANE:1:1'
      skull-hash: ''
      enchanted: false
      name: ''
      lore: []
      slots: '3,5'
      type: NONE
    filler_orange:
      material: 'STAINED_GLASS_PANE:2:1'
      skull-hash: ''
      enchanted: false
      name: ''
      lore: []
      slots: '10,11,12,13,14,15,16,19,22,25'
      type: NONE
    accept:
      material: 'STAINED_GLASS_PANE:5:1'
      skull-hash: ''
      enchanted: false
      name: '&a&l&nAccept'
      lore:
      - '&7The item will be extracted'
      - '&7if you can afford the operation.'
      - '&8&m                                              '
      - '&c&oDon''t forget to select'
      - '&c&othe item to extract!'
      slots: '8'
      type: ACCEPT
    exit:
      material: 'STAINED_GLASS_PANE:14:1'
      skull-hash: ''
      enchanted: false
      name: '&c&l&nCancel'
      lore: []
      slots: '0'
      type: EXIT