title: '&8&m           &8&l[ &9&lSettings &8&l]&8&m           '
size: 36
content:
  entity-names:
    material: 'NAME_TAG'
    name: '&eMob Names'
    lore:
    - '&bCurrent Mode: &a%entity-names%'
    - '&7'
    - '&7Toggling this option will'
    - '&7require the chunk update to'
    - '&7be affected for nearby entities.'
    - '&7'
    - '&6Left-Click: &eChange'
    type: SETTING_ENTITY_NAMES
    slots: 0

  player-helmet:
    material: 'GOLDEN_HELMET'
    name: '&eHelmet Invisibility'
    lore:
    - '&bCurrent: &a%player-helmet%'
    - '&7'
    - '&7Hides your helmet for'
    - '&7other players.'
    - '&c(but not for you)'
    - '&7'
    - '&6Left-Click: &eChange'
    item-flags:
    - '*'
    type: SETTING_PLAYER_HELMET
    slots: 1

  return:
    material: 'BARRIER'
    name: '&c&lReturn'
    type: RETURN
    slots: 31